### ISSUE TITLE
searchJobs() filtering by publishTimeRange isn't working properly

### ISSUE THREAD

**Issue by spernigotti** [googleapis/nodejs-talent#120]
I'm trying to search jobs filtering by publishTimeRange but it's not working properly, the results are not correct .
I tried using the API REST and in that case is working properly, seems like it's a problem of sdk.

#### Environment details

  - OS: Ubuntu 19.04
  - Node.js version: 10.5
  - npm version: 6.10
  - `@google-cloud/talent` version: 1.5

#### Steps to reproduce
```
const talent = require('@google-cloud/talent').v4beta1;
const jobClient = new talent.JobServiceClient();
const parent = jobClient.projectPath(PROJECT_ID);

(async() => {
	const options = { autoPaginate: false}
	const jobQuery = { publishTimeRange: { startTime: new Date(/* a date */) } };
	const [results,, metadata] = await jobClient.searchJobs({ parent, requestMetadata: { allowMissingIds: true }, jobQuery, offset: 0, pageSize: 10 }, options);

	console.log(resutls);
})();
```
Thanks!

**Comment by bcoe** [comment]
@spernigotti how do the results you're seeing differ from the rest request?

**Comment by spernigotti** [comment]
@bcoe the results are the same as without filters applied.

**Comment by bcoe** [comment]
@spernigotti mind trying:

```js
 (new Date()).getTime()
```

I'm not sure if we automatically convert to a timestamp, which is what it looks like the proto expects.

**Comment by spernigotti** [comment]
@bcoe I tried that but it returns a 500 code with the following body:
```
{
    "error": true,
    "message": ".google.cloud.talent.v4beta1.TimestampRange.startTime: object expected"
}
```
I also tried in ISO 8601 format as in the REST API, but I had the same error.

ISO example: `2019-10-31T06:48:38.454Z`

**Comment by callmehiphop** [comment]
Per the [proto files](https://github.com/googleapis/nodejs-talent/blob/master/protos/google/cloud/talent/v4beta1/common.proto#L37) it looks like both `startTime` and `endTime` need to be [`google.protobuf.Timestamp`](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#timestamp) objects. Typically they are structured like so

```js
const startTime = {
  seconds: 1549622069,
  nanos: 481320032
};
```

We also have a convenience module called [`PreciseDate`](https://github.com/googleapis/nodejs-precise-date) that can help create these structures from a date string.

```js
const publishTimeRange = {
  startTime: new PreciseDate('2019-10-31T06:48:38.454Z').toStruct()
};
```

@spernigotti mind giving one of these options a shot?

**Comment by spernigotti** [comment]
@callmehiphop you're right! with that format it's working ok.

**Comment by callmehiphop** [comment]
@spernigotti awesome, glad to hear it! I'm going to close this out then but let us know if there's anything else we can do to help 😎
