### ISSUE TITLE
{ autoPaginate: false } should be default

### ISSUE THREAD

**Issue by davidbiller** [googleapis/nodejs-talent#133]
https://cloud.google.com/talent-solution/job-search/docs/reference/rest/v4beta1/SearchJobsResponse?hl=de

If so specified in the docu, the response should also be default. 
I tried to specify pageSize and still got more jobs displayed.
Only after I set autoPaginate: false it worked and also the response had all fields that were specified in the docu. 

Alternatively, if pageSize is set, autoPaginate should be set to false.

**Comment by bcoe** [comment]
CC: @alexander-fenster food for thought, if we consider moving towards async iterators in the future.

**Comment by alexander-fenster** [comment]
The recommended way of querying the paginated resources is now using the `List...Async()` method and the `for await` iteration. That way it will only request as many records as needed.

Closing this as obsolete.
