### ISSUE TITLE
Search jobs return empty result

### ISSUE THREAD

**Issue by cuongnd273** [googleapis/nodejs-talent#426]
When I try run my API search job with this params
curl --request POST \
  'https://jobs.googleapis.com/v4/projects/resume-builder-c5c52/tenants/aefe42ea-1d00-0000-0000-00b857427f75/jobs:search?key=[YOUR_API_KEY]' \
  --header 'Authorization: Bearer [YOUR_ACCESS_TOKEN]' \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --data '{"jobQuery":{"query":"\"bartendar\""},"requestMetadata":{"allowMissingIds":true,"sessionId":"342342423432","userId":"4324234324"},"jobView":"JOB_VIEW_SMALL","maxPageSize":5,"orderBy":"posting_publish_time desc"}' \
  --compressed
It return response
{
  "metadata": {
    "requestId": "5d4d97b7-cab0-467a-847d-f134221058eb:APAb7ISE6cNQk7e8etAKIufY2p94vCGE3w=="
  }
}
Nothing job was find

**Comment by bcoe** [comment]
👋 hello @cuongnd273, this is a repository for an automatically generated client library based on the talent solutions API.

Your question regarding a curl request sounds like an issue regarding the API itself, you can open an issue [here](https://cloud.google.com/support/docs/issue-trackers) to ask your question of the team.
