### ISSUE TITLE
How to access enum values s.a EmploymentType.FULL_TIME ? 

### ISSUE THREAD

**Issue by kajiru** [googleapis/nodejs-talent#80]
I import the client library as follows: 
```
const talent = require('@google-cloud/talent').v4beta1;
```

sample use case: searching for jobs based on EmploymentTypes

```
const jobQuery = {
    // e.g: 
     jobQuery.employmentTypes = [EmploymentType.FULL_TIME]
};

```

**Comment by bcoe** [comment]
@kajiru for enums, I believe you should just be able to provide the string "FULL_TIME"; let me know if this does the trick for you?

**Comment by kajiru** [comment]
@bcoe That works, thanks!

**Comment by bcoe** [comment]
@kajiru awesome 👍 I'm glad you're unblocked.
